name: quantum-demo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - appmode
  - traitlets<5.10.0
  - pip
  - pip:
      - amplify-sched>=0.2.0
      - plotly<=5.24.1
      - numpy
      - ipywidgets
      - pandas
      - ipympl
      - networkx
